#!/usr/bin/env python3
"""Ingest the ServiceNow CSA "Study Items Checklist & Answers" (SNAF course)
into the quiz data as a separate pack under the CSA Certification path.

The questions below are hand-authored from the uploaded study checklist. Each
entry's `correct` indices are derived directly from the "answer" bullets in the
checklist and cross-checked against ServiceNow product facts. Where the source
PDF contained a known factual slip (e.g. it listed the ServiceNow founder as
"Bill Luddy"), the question uses the correct ServiceNow fact ("Fred Luddy") and
keeps the slip as a distractor — this is documented inline.

The script is idempotent: questions are keyed by stable ids (csa-snaf-NNN) and
re-running replaces them in place. It also registers a `snaf_checklist` mode on
the `csa` category in both category files.

It writes to both the root files (quiz-questions.json / quiz-categories.json)
and the data/quiz/* copies so the two stay in sync.
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
QUESTION_FILES = [REPO_ROOT / "quiz-questions.json", REPO_ROOT / "data/quiz/questions.json"]
CATEGORY_FILES = [REPO_ROOT / "quiz-categories.json", REPO_ROOT / "data/quiz/categories.json"]

SOURCE = "ServiceNow CSA Study Items Checklist (SNAF)"
SOURCE_SET = "snaf_checklist"
CATEGORY = "csa"

MODE = {
    "id": "snaf-pack",
    "name": "SNAF Study Checklist",
    "desc": "Knowledge-item quiz built from the ServiceNow CSA Study Items Checklist (SNAF course)",
    "count": "all",
    "timer": 0,
    "sourceSet": SOURCE_SET,
}


def Q(num, topic, difficulty, q, options, correct, explanation):
    """Build a question dict. `correct` is a list of 0-based option indices."""
    assert isinstance(correct, list) and correct, f"Q{num}: correct must be a non-empty list"
    assert all(0 <= c < len(options) for c in correct), f"Q{num}: correct index out of range"
    assert len(set(options)) == len(options), f"Q{num}: duplicate option text"
    item = {
        "id": f"csa-snaf-{num:03d}",
        "q": q,
        "type": "mcq",
        "difficulty": difficulty,
        "options": options,
        "correct": sorted(correct),
        "explanation": explanation,
        "source": SOURCE,
        "sourceSet": SOURCE_SET,
        "topic": topic,
    }
    if len(correct) > 1:
        item["multi"] = len(correct)
    return item


QUESTIONS = [
    # ── LD1: Platform Overview & Navigation ──────────────────────────────
    Q(1, "platform-overview", "easy",
      "Who is the founder of ServiceNow?",
      ["Fred Luddy", "Bill McDermott", "Bill Luddy", "Frank Slootman"],
      [0],
      "Fred Luddy founded ServiceNow. (Note: Bill McDermott is the current CEO, not the founder.)"),
    Q(2, "platform-overview", "easy",
      "Who is the current CEO of ServiceNow?",
      ["Bill McDermott", "Fred Luddy", "John Donahoe", "Frank Slootman"],
      [0],
      "Bill McDermott is the CEO of ServiceNow; Fred Luddy is the founder."),
    Q(3, "platform-overview", "medium",
      "Which set correctly lists the four ServiceNow workflows?",
      ["IT, Customer, Creator, and Employee Workflows",
       "IT, HR, Finance, and Security Workflows",
       "Incident, Problem, Change, and Request Workflows",
       "Now, Mobile, Portal, and Center Workflows"],
      [0],
      "The four ServiceNow workflows are IT Workflows, Customer Workflows, Creator Workflows, and Employee Workflows."),
    Q(4, "platform-overview", "medium",
      "Which of the following are ServiceNow user interfaces?",
      ["The Next Experience (Unified Navigation)", "Now Mobile App", "Service Portal", "Employee Center", "GlideRecord Console"],
      [0, 1, 2, 3],
      "The four ServiceNow interfaces are the Next Experience (Unified Navigation), Now Mobile App, Service Portal, and Employee Center."),
    Q(5, "platform-overview", "medium",
      "Which of these are the useful resources highlighted in the Welcome to ServiceNow module?",
      ["Now Learning", "ServiceNow Community", "ServiceNow Global Events", "ServiceNow Developer Site", "ServiceNow Store billing portal"],
      [0, 1, 2, 3],
      "The four useful resources are Now Learning, ServiceNow Community, ServiceNow Global Events, and the ServiceNow Developer Site."),
    Q(6, "itsm", "easy",
      "From the All menu, how do you navigate to create a new Incident?",
      ["All > Incident > Create New", "All > Self-Service > New Incident", "All > Service Desk > Create", "All > Tasks > New"],
      [0],
      "Use All > Incident > Create New to open a new incident form from the All menu."),
    Q(7, "itsm", "medium",
      "Which list correctly represents the Incident lifecycle states from New to Closed?",
      ["New, In Progress, On Hold, Resolved, Closed, Canceled",
       "New, Open, Pending, Work In Progress, Done",
       "Draft, Assigned, Active, Complete, Archived",
       "Open, Awaiting, Escalated, Solved, Ended"],
      [0],
      "Incident states progress through New, In Progress, On Hold, Resolved, Closed, and Canceled."),
    Q(8, "itsm", "easy",
      "Who can view Additional Comments entered on an Incident?",
      ["The requestor (they are customer-facing)",
       "Only fulfillers working the task",
       "Only system administrators",
       "Nobody — they are internal audit only"],
      [0],
      "Additional Comments are visible to the requestor, whereas Work Notes are viewable only within the task by fulfillers."),
    Q(9, "itsm", "easy",
      "On an Incident, who can view Work Notes?",
      ["Only users working within the task (internal)",
       "The requestor and the public",
       "Anyone with the ess role",
       "Only the assignment group manager"],
      [0],
      "Work Notes are viewable only within the task (internal). Additional Comments are the requestor-facing field."),
    Q(10, "itsm", "medium",
      "What happens when you set both Impact and Urgency to 1 on an Incident?",
      ["Priority is automatically set to 1 (Critical)",
       "The incident is automatically resolved",
       "The SLA is paused",
       "Nothing — Priority must always be set manually"],
      [0],
      "Setting Impact and Urgency to 1 automatically sets Priority to 1 (Critical) via the priority lookup matrix."),
    Q(11, "itsm", "easy",
      "Why do Incident SLAs exist?",
      ["They provide expected timing for ticket resolution based on Priority",
       "They automatically assign incidents to groups",
       "They store the incident's work notes",
       "They define which fields appear on the form"],
      [0],
      "SLAs provide expected timing for ticket resolution, driven by the incident's Priority."),
    Q(12, "platform-overview", "easy",
      "How do you navigate to the Service Operations Workspace?",
      ["Click Workspaces in the top header, then Service Operations Workspace",
       "All > Incident > Workspace",
       "All > Self-Service > Workspaces",
       "Right-click the form header and choose Workspace"],
      [0],
      "Workspaces are accessed from the Workspaces menu in the top header; select Service Operations Workspace."),
    Q(13, "self-service", "easy",
      "What is the All-menu path to the Employee Center portal?",
      ["All > Self-Service > Employee Center",
       "All > Service Portal > Employee",
       "All > Now Mobile > Center",
       "All > Workspaces > Employee Center"],
      [0],
      "The Employee Center portal is reached via All > Self-Service > Employee Center."),
    Q(14, "platform-overview", "medium",
      "What does a 'Baseline Implementation' refer to?",
      ["The base installation of ServiceNow prior to any configuration or customization",
       "A fully customized production instance",
       "The minimum number of users required to go live",
       "A backup taken before every upgrade"],
      [0],
      "Baseline implementation is the base installation of the environment before any configuration or customization is applied."),
    Q(15, "platform-overview", "medium",
      "Which statement best distinguishes Configuration from Customization?",
      ["Configuration uses built-in no-code functionality; customization adds functionality via plugins/scripts",
       "Configuration requires code; customization is always no-code",
       "Configuration is only for admins; customization is only for end users",
       "There is no difference between the two"],
      [0],
      "Configuration is what can be done without code using built-in functionality; customization adds functionality through plugins, scripts, etc."),
    Q(16, "platform-overview", "easy",
      "Which of these is one of the three environment types of ServiceNow instances?",
      ["Production", "Read-only", "Sandbox-only", "Public"],
      [0],
      "The three environment types are Production, Non-Production, and Dev/QA/UAT/Staging types."),
    Q(17, "platform-overview", "medium",
      "What does ServiceNow's single-tenant architecture mean?",
      ["Each instance has its own isolated database containing its data, applications, and customizations",
       "All customers share a single database",
       "Only one user can log in at a time",
       "Each instance can host only one application"],
      [0],
      "Single-tenant means each instance features an isolated database containing its own data, applications, and customizations."),
    Q(18, "platform-overview", "easy",
      "What is the minimum number of characters needed to start filtering results in the All menu search?",
      ["2 characters", "1 character", "3 characters", "5 characters"],
      [0],
      "A minimum of 2 characters is required before the All menu begins filtering applications and modules."),
    Q(19, "platform-overview", "medium",
      "How is role Elevation visually indicated in the interface?",
      ["A red border with an up arrow",
       "A green border with a lock",
       "A blue banner across the top",
       "A red border with an eye icon"],
      [0],
      "Elevation displays as a red border with an up arrow. (Impersonation shows a red border with an eye icon.)"),
    Q(20, "user-admin", "medium",
      "Which elevated role allows you to manage Access Controls?",
      ["security_admin", "workspace_admin", "catalog_admin", "knowledge_admin"],
      [0],
      "Elevating to security_admin grants the ability to manage Access Controls (ACLs)."),
    Q(21, "user-admin", "medium",
      "Which role(s) are required to perform impersonation?",
      ["admin or impersonator", "security_admin only", "itil only", "ess or user_admin"],
      [0],
      "Impersonation requires either the admin or the impersonator role."),
    Q(22, "platform-overview", "hard",
      "Which system property must be set to log impersonations in the System Log?",
      ["glide.sys.log_impersonation",
       "glide.ui.impersonation.enabled",
       "glide.security.log_impersonation",
       "glide.impersonate.audit"],
      [0],
      "Setting glide.sys.log_impersonation enables logging of impersonations in the System Log."),
    Q(23, "user-admin", "medium",
      "Which three roles are recommended for testing impersonation?",
      ["admin, ess, and itil", "admin, security_admin, and itil", "ess, itil, and approver_user", "admin, impersonator, and ess"],
      [0],
      "The recommended test roles are admin (test administrator), ess (Employee Self-Service / requester), and itil (process user)."),

    # ── LD2: Instance Configuration ──────────────────────────────────────
    Q(24, "user-admin", "medium",
      "Where do you navigate to update the Company logo?",
      ["All > System Properties > My Company",
       "All > User Administration > Companies",
       "All > System Definition > Plugins",
       "All > System Properties > Security"],
      [0],
      "The company logo is configured under All > System Properties > My Company."),
    Q(25, "user-admin", "medium",
      "Where do you navigate to update the Company name?",
      ["All > User Administration > Companies",
       "All > System Properties > My Company",
       "All > System Definition > Companies",
       "All > Self-Service > Organization"],
      [0],
      "The company name is updated under All > User Administration > Companies."),
    Q(26, "ui-config", "hard",
      "Which system property is set to TRUE to enable the dark theme?",
      ["glide.ui.polaris.dark_themes_enabled",
       "glide.ui.dark_mode_enabled",
       "glide.theme.dark.enabled",
       "glide.ui.polaris.theme"],
      [0],
      "Set glide.ui.polaris.dark_themes_enabled to TRUE to enable dark themes."),
    Q(27, "user-admin", "easy",
      "What is the All-menu path to view Plugins via System Definition?",
      ["All > System Definition > Plugins",
       "All > System Applications > Plugins",
       "All > System Properties > Plugins",
       "All > Plugins > Available"],
      [0],
      "Plugins are accessed via All > System Definition > Plugins."),
    Q(28, "user-admin", "medium",
      "Demo data should only be installed in which type of instance?",
      ["Non-production instances", "Production instances", "Any instance", "Only the Dev instance after go-live"],
      [0],
      "Demo data should only be installed in non-production instances."),
    Q(29, "user-admin", "medium",
      "What does Application Scoping protect?",
      ["It restricts access to an application's files and data from other applications/services",
       "It encrypts the instance database",
       "It limits how many users can log in",
       "It controls which browser can access the instance"],
      [0],
      "Application scoping restricts access to an application's files and data from other applications and services."),
    Q(30, "user-admin", "medium",
      "Which of the following are ServiceNow persona types?",
      ["System Administrator", "Specialized Administrator", "Process User", "Approver", "Database Owner"],
      [0, 1, 2, 3],
      "The five persona types are System Administrator, Specialized Administrator, Process User, Approver, and Requester."),
    Q(31, "user-admin", "medium",
      "On which system table does a User record exist?",
      ["sys_user", "sys_user_group", "sys_user_role", "sys_user_has_role"],
      [0],
      "Users are records on the sys_user table."),
    Q(32, "user-admin", "medium",
      "On which system table does a Group record exist?",
      ["sys_user_group", "sys_user", "sys_group", "sys_user_role"],
      [0],
      "Groups are records on the sys_user_group table."),
    Q(33, "user-admin", "medium",
      "On which system table does a Role record exist?",
      ["sys_user_role", "sys_role", "sys_user_group", "sys_security_role"],
      [0],
      "Roles are records on the sys_user_role table."),
    Q(34, "user-admin", "medium",
      "What is the ServiceNow best practice for assigning roles?",
      ["Create a group, assign the role to the group, then add users to the group",
       "Assign roles directly to each individual user",
       "Assign all roles to the admin and impersonate as needed",
       "Use only the itil role for everyone"],
      [0],
      "Best practice is to assign roles to a group and add users to that group rather than assigning roles directly to users."),
    Q(35, "user-admin", "hard",
      "When you assign a role, what else does the user receive?",
      ["The permissions of that role and any roles contained within it",
       "Only the single role, with no inherited permissions",
       "Admin access to the whole instance",
       "Access only after the next upgrade"],
      [0],
      "Assigning a role grants its permissions plus those of any contained roles (e.g., catalog_admin contains user_criteria_admin and catalog)."),

    # ── LD3: Configure Apps for Collaboration ────────────────────────────
    Q(36, "ui-config", "easy",
      "What does a List represent in ServiceNow?",
      ["A display of a set of records from a table",
       "The fields of a single record",
       "A predefined set of field choices",
       "A workflow of approval steps"],
      [0],
      "A List displays a list of records from a table."),
    Q(37, "ui-config", "medium",
      "Which are the three context menus available on a Classic list?",
      ["List Control Menu", "Column Options Menu", "Record Context Menu", "Form Design Menu"],
      [0, 1, 2],
      "The three Classic list context menus are the List Control Menu, the Column Options Menu, and the Record Context Menu."),
    Q(38, "ui-config", "easy",
      "What three components make up a filter condition?",
      ["Field, Operator, Value", "Table, Column, Row", "Name, Label, Value", "Trigger, Condition, Action"],
      [0],
      "A filter condition is made of a Field, an Operator, and a Value."),
    Q(39, "ui-config", "hard",
      "Which role is required to configure a List (add/remove/reorder columns) for all users?",
      ["personalize_list", "list_admin", "ui_admin", "view_admin"],
      [0],
      "The personalize_list role allows configuring a list layout for all users."),
    Q(40, "ui-config", "medium",
      "Where do you add new applications or modules via Application Menus?",
      ["All > System Definition > Application Menus",
       "All > System Properties > Menus",
       "All > UI Builder > Menus",
       "All > Self-Service > Applications"],
      [0],
      "Application Menus are managed under All > System Definition > Application Menus."),
    Q(41, "ui-config", "medium",
      "What does a View determine?",
      ["Which fields to display and in what order",
       "Which users can read a record",
       "The order business rules run",
       "Which table a form belongs to"],
      [0],
      "A View determines which fields are displayed and in what order."),
    Q(42, "ui-config", "medium",
      "Which of the following are the available viewing options for a Workspace List?",
      ["Grid Mode", "List Mode", "Open List in New Tab", "Schema Mode"],
      [0, 1, 2],
      "Workspace lists support Grid Mode, List Mode, and Open List in New Tab."),
    Q(43, "ui-config", "hard",
      "Which system property enables inline editing for Workspace lists?",
      ["glide.lists.inline_editing_enabled",
       "glide.ui.inline_edit",
       "glide.workspace.inline_editing",
       "glide.lists.edit_enabled"],
      [0],
      "glide.lists.inline_editing_enabled enables inline editing on workspace lists."),
    Q(44, "ui-config", "medium",
      "Which application is used to add a new Category and UX List for a workspace?",
      ["UI Builder", "Form Designer", "Flow Designer", "Report Designer"],
      [0],
      "UI Builder is used to add new Categories and UX Lists in a workspace."),
    Q(45, "ui-config", "easy",
      "What does a Form display?",
      ["Fields from a single record",
       "A list of records from a table",
       "A predefined choice list",
       "A dependency map of CIs"],
      [0],
      "A Form displays the fields from a single record."),
    Q(46, "ui-config", "medium",
      "How do Form Design and Form Layout differ?",
      ["Form Design is a visual drag-and-drop interface; Form Layout uses a List Collector with –split– markers",
       "Form Design requires scripting; Form Layout is visual",
       "They are identical interfaces with different names",
       "Form Layout supports dot-walking while Form Design does not allow any fields"],
      [0],
      "Form Design is a visual drag-and-drop interface, while Form Layout uses a List Collector with –split–/–end split– markers to control columns."),
    Q(47, "ui-config", "hard",
      "Which capability is NOT available in the List Collector when using Form Design?",
      ["Dot-walking", "Adding fields", "Reordering fields", "Removing fields"],
      [0],
      "Dot-walking is not available in the List Collector when using Form Design."),
    Q(48, "ui-config", "hard",
      "Which system property disables Personalize Form for the itil role (restricting it to admin)?",
      ["glide.ui.personalize_form.role = admin",
       "glide.ui.form.personalize = false",
       "glide.form.personalize.role = itil",
       "glide.ui.personalize.disabled = true"],
      [0],
      "Setting glide.ui.personalize_form.role = admin limits Personalize Form to the admin role."),
    Q(49, "ui-config", "medium",
      "Which are the three main components of the Form Designer?",
      ["Page Header", "Field Navigator", "Form Layout", "Activity Stream"],
      [0, 1, 2],
      "The Form Designer's three main components are the Page Header, the Field Navigator, and the Form Layout."),
    Q(50, "ui-config", "medium",
      "What is a Formatter?",
      ["A form element that displays information that is not a field in a record",
       "A script that formats date values",
       "A type of reference field",
       "A tool that exports forms to PDF"],
      [0],
      "A formatter is a form element that displays information which is not a field in the record (e.g., the activity stream)."),
    Q(51, "ui-config", "easy",
      "What is a Choice List?",
      ["A field type that lets the user select from a predefined set of choices",
       "A field that stores the sys_id of a referenced record",
       "A list of all tables in the instance",
       "A list of users in a group"],
      [0],
      "A choice list is a field type that lets a user select from a predefined set of choices."),
    Q(52, "ui-config", "medium",
      "What is a Reference field/list?",
      ["A field type that lets the user select a value from referenced records",
       "A field that holds free-text only",
       "A list of report categories",
       "A predefined set of static choices"],
      [0],
      "A reference field lets the user select a value from records on a referenced table; clicking the magnifying glass opens the list."),

    # ── LD3 / MD5: Enable Productivity ──────────────────────────────────
    Q(53, "reporting", "easy",
      "What is the All-menu path to access and run Reports?",
      ["All > Reports > View/Run",
       "All > Self-Service > Reports",
       "All > Reporting > Designer",
       "All > Dashboards > Reports"],
      [0],
      "Reports are accessed via All > Reports > View/Run."),
    Q(54, "reporting", "medium",
      "Which are the Report visibility controls in the Reports > View/Run module?",
      ["My Reports", "Group", "Global", "All"],
      [0, 1, 2, 3],
      "The visibility controls are My Reports, Group, Global, and All."),
    Q(55, "reporting", "medium",
      "Which are the four sections of the Report Designer (in order)?",
      ["Data, Type, Configure, Style",
       "Source, Layout, Filter, Save",
       "Data, Filter, Group, Style",
       "Type, Data, Style, Share"],
      [0],
      "The Report Designer has four sections: Data, Type, Configure, and Style."),
    Q(56, "reporting", "medium",
      "What is the key difference between standard Reporting and Performance Analytics?",
      ["Reporting shows the current state; Performance Analytics reviews historic trends and forecasts the future",
       "Reporting is real-time; Performance Analytics cannot show any time data",
       "Reporting forecasts the future; Performance Analytics only shows current data",
       "There is no difference"],
      [0],
      "Reporting answers 'Where are we now?' (current state), while Performance Analytics reviews trends over time and forecasts ('Where have we been / where are we going?')."),
    Q(57, "reporting", "easy",
      "What is the All-menu path to access Dashboards?",
      ["All > Self-Service > Dashboards",
       "All > Reports > Dashboards",
       "All > Dashboards > View",
       "All > Reporting > Dashboards"],
      [0],
      "Dashboards are accessed via All > Self-Service > Dashboards."),
    Q(58, "reporting", "medium",
      "Which are the three options for the 'Viewable by' field on a Tag?",
      ["Me", "Groups and Users", "Everyone", "Roles only"],
      [0, 1, 2],
      "The three Viewable by options are Me, Groups and Users, and Everyone (Everyone requires a role)."),
    Q(59, "ui-config", "medium",
      "Which role grants the ability to create and share Form Templates?",
      ["template_editor_group", "form_admin", "ui_admin", "personalize_form"],
      [0],
      "The template_editor_group role grants the ability to create and share form templates."),
    Q(60, "itsm", "easy",
      "What is the All-menu path to the My Work module?",
      ["All > Service Desk > My Work",
       "All > Self-Service > My Work",
       "All > Tasks > My Work",
       "All > Incident > My Work"],
      [0],
      "My Work is accessed via All > Service Desk > My Work (and My Group's Work alongside it)."),
    Q(61, "ui-config", "medium",
      "What are the two types of Visual Task Boards (VTBs)?",
      ["Free-form and data-driven",
       "Static and dynamic",
       "Personal and shared",
       "Classic and workspace"],
      [0],
      "VTBs are either free-form (fully customizable personal organizer) or data-driven (tied to data; lane titles cannot change)."),
    Q(62, "ui-config", "hard",
      "What is the standard syntax used to reference a field value in a Quick Message body?",
      ["{table_name.variable_name}",
       "${variable_name}",
       "[table_name:variable_name]",
       "gs.getValue(variable_name)"],
      [0],
      "Quick Messages reference field values using {table_name.variable_name}."),
    Q(63, "reporting", "medium",
      "Which three methods can a Notification use to alert users?",
      ["Email", "SMS", "Meeting Invitation", "Push to MID Server"],
      [0, 1, 2],
      "Notifications can be sent via Email, SMS, or Meeting Invitation."),
    Q(64, "reporting", "easy",
      "What is the All-menu path to Email Notifications?",
      ["All > System Notifications > Email > Notifications",
       "All > System Policy > Email > Notifications",
       "All > Email Client > Notifications",
       "All > System Properties > Notifications"],
      [0],
      "Email notifications are managed at All > System Notifications > Email > Notifications."),
    Q(65, "reporting", "medium",
      "Which are the three tabs required to create a Notification?",
      ["When to send", "Who will receive", "What it will contain", "Where to log"],
      [0, 1, 2],
      "The three notification tabs are When to send, Who will receive, and What it will contain."),
    Q(66, "reporting", "hard",
      "How many characters make up a Notification Watermark label?",
      ["31 characters", "21 characters", "20 characters", "7 characters"],
      [0],
      "A watermark is 31 characters: a 3-char customizable prefix, a 7-char source record identifier, and an underscore plus a 20-char random string."),
    Q(67, "reporting", "medium",
      "From which release onward is the Sidebar available?",
      ["Tokyo or later", "San Diego or later", "Rome or later", "Quebec or later"],
      [0],
      "The Sidebar is only available in Tokyo or later releases."),

    # ── LD3 / MD6: Manage an Instance ───────────────────────────────────
    Q(68, "platform-overview", "medium",
      "Which are the four types of Instance Scan Checks?",
      ["Table check", "Column Type check", "Script Only check", "Linter Check", "Form check"],
      [0, 1, 2, 3],
      "Instance Scan checks come in four types: Table, Column Type, Script Only, and Linter checks."),
    Q(69, "platform-overview", "medium",
      "On an Instance Scan, what does a Check score of 100 indicate?",
      ["The check passed and there is no record on the findings list",
       "The check failed with the maximum number of exceptions",
       "The scan has not yet run",
       "All 100 records were scanned successfully"],
      [0],
      "A score of 100 means the check passed (no finding). A score below 100 means there are exceptions and a finding record exists."),
    Q(70, "platform-overview", "medium",
      "What is a ServiceNow 'Family'?",
      ["A set of releases named after a major city (e.g., Tokyo)",
       "A group of related plugins",
       "A collection of user roles",
       "A set of tables that extend Task"],
      [0],
      "A family is a set of releases named after a major city, such as Tokyo."),
    Q(71, "platform-overview", "medium",
      "What is the difference between Upgrading and Updating?",
      ["Upgrading moves to a release in a different family; updating moves between patches/hotfixes within the same family",
       "Upgrading is for patches; updating moves between families",
       "They are the same operation",
       "Upgrading only changes the UI theme"],
      [0],
      "Upgrading is moving to a release in a different family; updating is moving from one patch/hotfix to another within the same family."),
    Q(72, "platform-overview", "medium",
      "What is the default Rollback window for a ServiceNow upgrade?",
      ["10 days", "30 days", "7 days", "There is no time limit"],
      [0],
      "The rollback window is 10 days by default; ServiceNow does not provide a universal rollback option, so you must contact Support."),

    # ── LD4: Self Service & Automation ──────────────────────────────────
    Q(73, "knowledge-mgmt", "medium",
      "Which role is required to administer Knowledge Bases?",
      ["knowledge_admin", "knowledge_manager", "kb_admin", "knowledge"],
      [0],
      "The knowledge_admin role is required to administer Knowledge Bases."),
    Q(74, "knowledge-mgmt", "easy",
      "What is the All-menu path to access Knowledge?",
      ["All > Self-Service > Knowledge",
       "All > Knowledge > View",
       "All > Self-Service > Knowledge Bases",
       "All > Service Desk > Knowledge"],
      [0],
      "Knowledge is accessed at All > Self-Service > Knowledge."),
    Q(75, "knowledge-mgmt", "medium",
      "How many Knowledge Bases can a single article be associated with?",
      ["One", "Two", "Unlimited", "As many as its categories"],
      [0],
      "Only one article can be associated to a Knowledge Base relationship — each article belongs to a single KB, while a KB can have many categories."),
    Q(76, "knowledge-mgmt", "medium",
      "Which are the four basic outcomes when managing access through User Criteria records?",
      ["canRead", "cantRead", "canContribute", "cantContribute", "canRetire"],
      [0, 1, 2, 3],
      "User Criteria outcomes are canRead, cantRead, canContribute, and cantContribute."),
    Q(77, "knowledge-mgmt", "hard",
      "Which system property ensures all logged-in users have access to Knowledge Bases when no user criteria are defined?",
      ["glide.knowman.block_access_with_no_user_criteria",
       "glide.knowman.public_access",
       "glide.kb.all_users_access",
       "glide.knowman.default_read"],
      [0],
      "glide.knowman.block_access_with_no_user_criteria controls KB access when no user criteria exist."),
    Q(78, "service-catalog", "easy",
      "What is the All-menu path to the Service Catalog?",
      ["All > Self-Service > Service Catalog",
       "All > Service Catalog > View",
       "All > Self-Service > Catalog Builder",
       "All > Catalog > Items"],
      [0],
      "The Service Catalog is accessed at All > Self-Service > Service Catalog."),
    Q(79, "service-catalog", "medium",
      "Which role is required to manage a Service Catalog?",
      ["catalog_admin", "catalog_manager", "sc_admin", "itil_admin"],
      [0],
      "The catalog_admin role is required to manage a Service Catalog."),
    Q(80, "service-catalog", "medium",
      "Which records are created once a Service Catalog order is placed?",
      ["REQ (Request)", "RITM (Request Item)", "SCTASK (Catalog Task)", "INC (Incident)"],
      [0, 1, 2],
      "Placing an order creates a REQ (Request), one or more RITM (Request Items), and SCTASK (Catalog Tasks)."),
    Q(81, "service-catalog", "hard",
      "Which table prefix/name pairing is correct?",
      ["Request → REQ → sc_request",
       "Request Item → RITM → sc_task",
       "Catalog Task → SCTASK → sc_req_item",
       "Request → REQ → sc_req_item"],
      [0],
      "Request = REQ = sc_request; Request Item = RITM = sc_req_item; Catalog Task = SCTASK = sc_task."),
    Q(82, "service-catalog", "medium",
      "What is a Record Producer used for?",
      ["A simplified form that translates user input into task-based records",
       "A report that produces records on a schedule",
       "A business rule that inserts records",
       "A workflow that approves records"],
      [0],
      "A record producer is a simplified form that lets a user enter information that is translated into task-based records."),
    Q(83, "service-catalog", "medium",
      "What is the benefit of an Order Guide?",
      ["It lets you order multiple related items as a single request",
       "It restricts who can view a catalog item",
       "It generates SLAs for catalog tasks",
       "It validates variables on submit"],
      [0],
      "An order guide provides the ability to order multiple, related items as a single request."),
    Q(84, "service-catalog", "medium",
      "Which of the following are major components of the Service Catalog?",
      ["Catalog Items", "Variables", "Variable Sets", "Record Producers", "Business Rules"],
      [0, 1, 2, 3],
      "The five major components are Catalog Items, Variables, Variable Sets, Record Producers, and Flows."),
    Q(85, "workflow-automation", "easy",
      "What is the All-menu path to Flow Designer?",
      ["All > Process Automation > Flow Designer",
       "All > Workflow > Flow Designer",
       "All > Flow Designer > Designer",
       "All > Self-Service > Flow Designer"],
      [0],
      "Flow Designer is accessed at All > Process Automation > Flow Designer."),
    Q(86, "workflow-automation", "medium",
      "Which three roles are used to work with Flow Designer?",
      ["flow_designer", "flow_operator", "action_designer", "flow_admin"],
      [0, 1, 2],
      "The three Flow Designer roles are flow_designer, flow_operator, and action_designer."),
    Q(87, "workflow-automation", "medium",
      "What are the four main components of a Flow?",
      ["Triggers, Conditions, Actions, Data",
       "Tables, Records, Fields, Views",
       "When, Who, What, Where",
       "Inputs, Steps, Outputs, Logs"],
      [0],
      "A flow's four main components are Triggers, Conditions, Actions, and Data."),
    Q(88, "workflow-automation", "easy",
      "What is the Virtual Agent?",
      ["A conversational platform that helps users get information and perform tasks via a messaging interface",
       "A scheduled job that closes incidents",
       "A reporting dashboard",
       "A MID Server component"],
      [0],
      "The Virtual Agent is a conversational platform that helps users obtain information, make decisions, and perform common tasks within a messaging interface."),

    # ── LD5: Database Management ─────────────────────────────────────────
    Q(89, "tables-schema", "easy",
      "Which three elements make up the ServiceNow data infrastructure?",
      ["Tables, Records, Fields",
       "Forms, Lists, Views",
       "Applications, Modules, Menus",
       "Triggers, Conditions, Actions"],
      [0],
      "The ServiceNow infrastructure includes Tables, Records, and Fields."),
    Q(90, "tables-schema", "medium",
      "How are records uniquely identified in ServiceNow, and where is the System Dictionary?",
      ["By a sys_id; All > System Definition > Dictionary",
       "By a number field; All > System Properties > Dictionary",
       "By a sys_id; All > System Security > Dictionary",
       "By their name; All > System Definition > Tables & Columns"],
      [0],
      "Records are identified by a sys_id, and the System Dictionary is at All > System Definition > Dictionary."),
    Q(91, "tables-schema", "medium",
      "Which of the following are forms of table relationships?",
      ["One-to-many", "Many-to-many", "Database View", "Extensions", "One-to-one mirror"],
      [0, 1, 2, 3],
      "The four forms of table relationships are One-to-many, Many-to-many, Database View, and Extensions."),
    Q(92, "tables-schema", "medium",
      "What does a Reference field store?",
      ["The sys_id of a record on another table",
       "The display value of a record as text",
       "A list of choices",
       "A JSON payload"],
      [0],
      "A reference field stores the sys_id of a record on another table, establishing the reference relationship."),
    Q(93, "tables-schema", "medium",
      "In table inheritance, what is true of a child table?",
      ["It extends the parent table and inherits all of its fields",
       "It cannot have any of the parent's fields",
       "It must be in a different application scope",
       "It replaces the parent table"],
      [0],
      "A child table extends from the parent and inherits all of the parent's fields."),
    Q(94, "tables-schema", "hard",
      "Which statement correctly describes Base, Core, and Custom tables?",
      ["Base: can have children but no parent; Core: can have both parent and child; Custom: created by admins/developers",
       "Base: created by developers; Core: no relationships; Custom: ships with the platform",
       "Base and Core are identical; Custom tables cannot be extended",
       "Core tables cannot have child tables"],
      [0],
      "A Base table can have children but no parent; a Core table (ships in base system) can have both parent and child relationships; Custom tables are created by admins/developers."),
    Q(95, "user-admin", "medium",
      "Which are the three levels of security checked before an end user can perform CRUD operations on a table?",
      ["User Authentication", "Application/Module access (Roles)", "Database access (ACLs)", "Network firewall"],
      [0, 1, 2],
      "The three levels are User Authentication, Application/Module access (Roles), and Database access (Access Control Rules)."),
    Q(96, "user-admin", "medium",
      "Which role is required to manage the Access Control List (ACL)?",
      ["security_admin", "admin", "user_admin", "acl_admin"],
      [0],
      "Managing the ACL at All > System Security > Access Control requires the security_admin role (via elevation)."),
    Q(97, "user-admin", "medium",
      "Which three elements define an Access Control?",
      ["Operation", "Object", "Permissions", "Trigger"],
      [0, 1, 2],
      "An Access Control is defined by an Operation, an Object, and Permissions."),
    Q(98, "user-admin", "medium",
      "Which four Access Controls are generated by default when a custom table is created?",
      ["Create", "Read", "Write", "Delete", "Query"],
      [0, 1, 2, 3],
      "Creating a custom table generates Create, Read, Write, and Delete access controls (plus an associated role)."),
    Q(99, "user-admin", "hard",
      "Which ACL rule type applies to all fields that do NOT have a specific table.field rule?",
      ["table.*", "table.–none–", "table.field", "table.all"],
      [0],
      "table.* applies to all fields without a specific table.field rule; table.–none– applies to the whole table; table.field applies to a specific field."),
    Q(100, "user-admin", "hard",
      "When writing ACLs, which rule type actually grants access to records?",
      ["The –none– (whole table) access control",
       "The table.* access control",
       "The table.field access control",
       "Any active ACL on the table"],
      [0],
      "Only the –none– access control grants access to records, which is why a –none– rule should accompany a table.* rule."),
    Q(101, "import-integration", "medium",
      "Which of the following are supported Import Set data sources?",
      ["CSV", "XML", "Excel", "JDBC", "PDF"],
      [0, 1, 2, 3],
      "Supported data sources are CSV, XML, Excel, JDBC, and HTTP/FTP. (PDF is not a supported import source.)"),
    Q(102, "import-integration", "medium",
      "What is the difference between an Import Set Table and a Transform Map?",
      ["The Import Set Table is a staging area for imported records; the Transform Map guides moving data to the target table",
       "The Import Set Table is the target table; the Transform Map is the source file",
       "They are two names for the same object",
       "The Transform Map stores raw data; the Import Set Table maps fields"],
      [0],
      "The Import Set Table is a staging area for imported records, and the Transform Map provides the guide for moving data from the import set to the target table."),
    Q(103, "import-integration", "medium",
      "Why would you use Coalesce during a transform?",
      ["To specify a field as a unique key so existing records update instead of creating duplicates",
       "To merge two tables into one",
       "To delete the import set after transform",
       "To convert Excel to CSV automatically"],
      [0],
      "Coalesce designates a field (or fields) as a unique key so existing records are updated rather than inserted as duplicates."),
    Q(104, "cmdb", "medium",
      "Which three system tables pertain to the CMDB?",
      ["cmdb", "cmdb_ci", "cmdb_rel_ci", "cmdb_model"],
      [0, 1, 2],
      "The three key CMDB tables are cmdb, cmdb_ci, and cmdb_rel_ci."),
    Q(105, "cmdb", "easy",
      "What does CMDB stand for?",
      ["Configuration Management Database",
       "Change Management Database",
       "Customer Management Database",
       "Cloud Management Database"],
      [0],
      "CMDB stands for Configuration Management Database."),
    Q(106, "cmdb", "easy",
      "What is the All-menu path to the CI Class Manager?",
      ["All > Configuration > CI Class Manager",
       "All > CMDB > CI Class Manager",
       "All > Configuration > Class Manager",
       "All > System Definition > CI Class Manager"],
      [0],
      "The CI Class Manager is at All > Configuration > CI Class Manager."),
    Q(107, "cmdb", "medium",
      "What is the CSDM model?",
      ["A set of standard terms and conditions governing a CMDB-based framework",
       "An automatic fix for past CMDB implementations",
       "A process and implementation guide for ITSM",
       "A SKU/product you purchase from ServiceNow"],
      [0],
      "CSDM is a set of terms and conditions (standard definitions and best practices) governing a CMDB-based framework. It is not a process guide, not code to install, and not a product to buy."),
    Q(108, "cmdb", "medium",
      "What is the difference between top-down (Service) Mapping and horizontal Discovery?",
      ["Top-down mapping overlays service maps to connect CIs underlying a service; horizontal discovery inventories devices/apps without showing dependencies",
       "Top-down mapping inventories devices; horizontal discovery connects services",
       "They produce identical results",
       "Horizontal discovery only works in non-production"],
      [0],
      "Top-down (service) mapping overlays service maps to connect the CIs underlying a service, while horizontal discovery creates an inventory of devices/applications without showing how they are connected."),

    # ── LD6: Data Migration & Integration ───────────────────────────────
    Q(109, "scripting", "medium",
      "Which of the following are the four types of Client Scripts?",
      ["onCellEdit()", "onChange()", "onLoad()", "onSubmit()", "onDisplay()"],
      [0, 1, 2, 3],
      "The four client script types are onCellEdit(), onChange(), onLoad(), and onSubmit()."),
    Q(110, "scripting", "easy",
      "What scripting language is used in ServiceNow?",
      ["JavaScript", "Python", "Java", "Groovy"],
      [0],
      "ServiceNow scripting is performed in JavaScript."),
    Q(111, "scripting", "medium",
      "Where do client-side and server-side scripts execute, respectively?",
      ["Client-side runs in the web browser; server-side runs on the ServiceNow database",
       "Client-side runs on the database; server-side runs in the browser",
       "Both run only in the browser",
       "Both run only on the MID Server"],
      [0],
      "Client-side scripts run in the web browser; server-side scripts run on the ServiceNow database/server."),
    Q(112, "ui-config", "medium",
      "Which three UI Policy Actions can be applied with a UI Policy?",
      ["Mandatory or Optional", "Hidden or Visible", "Read-only or Editable", "Locked or Unlocked"],
      [0, 1, 2],
      "A UI Policy can set fields Mandatory/Optional, Hidden/Visible, and Read-only/Editable."),
    Q(113, "ui-config", "hard",
      "How does a Data Policy differ from a UI Policy?",
      ["UI Policies are enforced only on data entered into a form; Data Policies are enforced on all data entered into the platform",
       "Data Policies only work in workspaces; UI Policies only work in Classic",
       "UI Policies enforce all data; Data Policies enforce only form data",
       "They are functionally identical"],
      [0],
      "UI Policies are enforced only on data entered into a form, whereas Data Policies enforce data consistency on all data entered into the platform."),
    Q(114, "scripting", "medium",
      "A Business Rule can be configured to run when a record is...?",
      ["displayed, inserted, updated, or deleted (or when the table is queried)",
       "only inserted",
       "only when a user logs in",
       "only on a schedule"],
      [0],
      "A Business Rule can run when a record is displayed, inserted, updated, deleted, or when a table is queried."),
    Q(115, "service-catalog", "medium",
      "Which are the three 'When to Run' options for a Catalog UI Policy?",
      ["onLoad()", "onChange()", "onSubmit()", "onCellEdit()"],
      [0, 1, 2],
      "Catalog UI Policies run onLoad(), onChange(), or onSubmit()."),
    Q(116, "update-sets", "medium",
      "What is an Update Set?",
      ["A group of configuration changes that can be moved from one instance to another",
       "A backup of the entire instance database",
       "A set of user roles bundled together",
       "A collection of scheduled jobs"],
      [0],
      "An Update Set is a group of configuration changes that can be moved from one instance to another."),
    Q(117, "update-sets", "hard",
      "Which system table stores all the tracked configuration changes for update sets?",
      ["sys_update_xml", "sys_update_set", "sys_metadata", "sys_audit"],
      [0],
      "Tracked table changes are stored in sys_update_xml."),
    Q(118, "update-sets", "easy",
      "What is the All-menu path to view existing (local) Update Sets?",
      ["All > System Update Sets > Local Update Sets",
       "All > System Definition > Update Sets",
       "All > System Update Sets > Retrieved Update Sets",
       "All > Update Sets > Local"],
      [0],
      "Local update sets are viewed at All > System Update Sets > Local Update Sets."),
    Q(119, "update-sets", "medium",
      "What is and is not captured within an Update Set?",
      ["Process (configuration) records are captured; data is not",
       "Data is captured; configuration records are not",
       "Both data and configuration are always captured",
       "Neither data nor configuration is captured"],
      [0],
      "Update Sets capture process/configuration records but not data; use the Export XML function to move data manually."),
    Q(120, "update-sets", "medium",
      "What is the typical three-step process for retrieving an Update Set?",
      ["Retrieve, Preview, Commit",
       "Import, Validate, Publish",
       "Load, Transform, Commit",
       "Export, Retrieve, Apply"],
      [0],
      "The retrieval process is Retrieve, Preview, then Commit."),
    Q(121, "update-sets", "hard",
      "During Preview of an Update Set, which field is matched on platform records?",
      ["sys_id", "number", "sys_created_on", "name"],
      [0],
      "During preview, sys_id fields are matched on the platform records."),
    Q(122, "scripting", "medium",
      "What is the primary purpose of the Automated Test Framework (ATF)?",
      ["To create and run automated tests on your instance after modifying it",
       "To automatically upgrade the instance",
       "To import data from external sources",
       "To generate reports and dashboards"],
      [0],
      "ATF lets you create and run automated tests after modifying an instance, reducing manual testing and keeping test instances clean via rollback."),
]


def load(path):
    with open(path) as f:
        return json.load(f)


def dump(path, data):
    with open(path, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def merge_questions(path):
    data = load(path)
    csa = data.get(CATEGORY, [])
    by_id = {q["id"]: i for i, q in enumerate(csa)}
    added = replaced = 0
    for q in QUESTIONS:
        if q["id"] in by_id:
            csa[by_id[q["id"]]] = q
            replaced += 1
        else:
            csa.append(q)
            added += 1
    data[CATEGORY] = csa
    dump(path, data)
    return added, replaced


def register_mode(path):
    data = load(path)
    cat = data.get(CATEGORY)
    if not cat:
        raise SystemExit(f"{path}: no '{CATEGORY}' category found")
    modes = cat.setdefault("modes", [])
    for i, m in enumerate(modes):
        if m.get("id") == MODE["id"]:
            modes[i] = MODE
            break
    else:
        modes.append(MODE)
    dump(path, data)


def main():
    for p in QUESTION_FILES:
        a, r = merge_questions(p)
        print(f"{p}: +{a} added, {r} replaced (total SNAF questions in pack: {len(QUESTIONS)})")
    for p in CATEGORY_FILES:
        register_mode(p)
        print(f"{p}: registered mode '{MODE['id']}'")


if __name__ == "__main__":
    main()
