"""Apply doc-validated corrections to CSA question bank.

Each entry in FIXES is keyed by question id and specifies one of:
  - new_correct: replacement list[int] for q.correct
  - new_options: replacement list[str] for q.options
  - drop_choose_n: if True, strip "(Choose N.)" stem and remarks for safety
  - explanation: optional explanation text added

The script applies the fixes to BOTH `quiz-questions.json` and
`data/quiz/questions.json` so the loader sees consistent data.

Sources for the answer choices below are summarized in
`csa-validation-report.json` generated by this same run.
"""
import json
import re
from copy import deepcopy

# ---------- FIXES ----------
# Multi-select Choose-N fixes (correct[] only).
# Indices refer to the order of options on the question as stored.
CHOOSE_N = {
    # Shared Responsibility Model — customer: Auth + Data encryption at rest
    "csa-snow-CSA-Q5-b1":   [1, 3],
    # UI Policy Action attributes — Mandatory, Visible, Read-Only
    "csa-snow-CSA-Q8-b1":   [1, 2, 4],
    # Table Builder roles — app_engine_admin + admin
    "csa-snow-CSA-Q9-b1":   [2, 3],
    # CMDB concepts — Service Processes, Tables/Fields, Database, Dependency View
    "csa-snow-CSA-Q17-b1":  [0, 2, 3, 4],
    # Form Design interface components — Field Navigator, Field Picker, Form Layout
    "csa-snow-CSA-Q19-b1":  [2, 3, 4],
    # Notification methods — Meeting Invitation, Email, SMS
    "csa-snow-CSA-Q20-b1":  [0, 1, 4],
    # Business Rule fields to specify — Table, Script, Timing, Condition
    "csa-snow-CSA-Q24-b1":  [1, 4, 7, 8],
    # Open Context Menu — Right-click + Context Menu icon
    "csa-snow-CSA-Q28-b1":  [2, 4],
    # Task→Incident→Super Incident hierarchy — 5 correct relationships
    "csa-snow-CSA-Q32-b1":  [1, 5, 6, 7, 8],
    # Related list buttons — Add, Edit, New
    "csa-snow-CSA-Q37-b1":  [0, 1, 4],
    # KB categories — Managers + Owners
    "csa-snow-CSA-Q41-b1":  [3, 6],
    # Basic Config UI16 — Banner Image, Browser Tab Title, System Date Format
    "csa-snow-CSA-Q46-b1":  [0, 2, 3],
    # KB search sort — Most recent, Popularity, Relevancy
    "csa-snow-CSA-Q51-b1":  [0, 1, 2],
    # Reports created from — List column heading + Statistics module
    "csa-snow-CSA-Q52-b1":  [0, 2],
    # User menu — Log Out, Elevate Roles, Impersonate Users
    "csa-snow-CSA-Q55-b1":  [1, 2, 3],
    # Related list examples — HR Case->Parent, Catalog Task->Parent, Outage->Task number
    "csa-snow-CSA-Q57-b1":  [1, 2, 3],
    # UI16 attributes (5) — Browser tab title, Module text color, Base theme, Header background color, Banner Image
    "csa-snow-CSA-Q81-b1":  [0, 1, 3, 6, 7],
    # Flow Designer core actions — Create Record, Ask for Approval, Look Up Record, Wait for Condition
    "csa-snow-CSA-Q82-b1":  [1, 2, 3, 4],
    # New IT employee groups — Create User Account, Add to Hardware, Add to Network
    "csa-snow-CSA-Q86-b1":  [0, 2, 4],
    # List UI Actions — List Links, List Choices, List Buttons, List Context Menu
    "csa-snow-CSA-Q89-b1":  [0, 1, 2, 4],
    # NOT in Update Set by default — Homepages, Data, Published Workflows, Report Definitions
    "csa-snow-CSA-Q93-b1":  [0, 1, 2, 7],
    # Auto-created ACLs on custom table — create, delete, read, write
    "csa-snow-CSA-Q98-b1":  [0, 1, 4, 5],
    # Impersonate roles — impersonator + admin
    "csa-snow-CSA-Q114-b1": [2, 4],
    # Flow Designer benefits — Natural-language, No-code, 3rd party integration
    "csa-snow-CSA-Q116-b1": [3, 4, 5],
    # UI Policy consistency — Hidden, Read-only, Mandatory
    "csa-snow-CSA-Q130-b1": [2, 3, 4],
    # eCommerce tracking — Discovery, CMDB, Service Mapping
    "csa-snow-CSA-Q132-b1": [1, 2, 3],
    # Group assignment benefits — My Groups Work, on-call, skills, availability
    "csa-snow-CSA-Q142-b1": [0, 1, 3, 5],
    # Create table modules — Tables + Tables & Columns
    "csa-snow-CSA-Q156-b1": [2, 3],
    # Two ways to generate Event — Business Rule + Workflow
    "csa-snow-CSA-Q168-b1": [0, 1],
    # Best practice — Add users to groups + Assign roles to groups
    "csa-snow-CSA-Q169-b1": [2, 3],
    # ACL permissions — Roles, Conditional Expressions, Scripts
    "csa-snow-CSA-Q176-b1": [0, 1, 3],
    # Auth methods — Local database, LDAP, SSO
    "csa-snow-CSA-Q177-b1": [1, 2, 3],
    # Reports page sections — Group, My reports, Global, All
    "csa-snow-CSA-Q196-b1": [0, 2, 5, 8],
    # Data Source types — Local Sources, JDBC, Network Server, LDAP
    "csa-snow-CSA-Q201-b1": [0, 3, 4, 5],
    # Form UI Actions — Buttons, Context Menu, Links
    "csa-snow-CSA-Q204-b1": [2, 3, 4],
    # Change Priority label — Configure Label + Configure Dictionary
    "csa-snow-CSA-Q208-b1": [0, 1],
    # Extended table fields — fields not in base + specific to extended (these are the same idea twice in the dump,
    # but the question lists them both as options; the CSA-cert canonical pair is 0+2)
    "csa-snow-CSA-Q209-b1": [0, 2],
    # Task assignment entities — Users + Groups
    "csa-snow-CSA-Q214-b1": [0, 2],
    # Self Service only — No itil role + not in itil-role group
    "csa-snow-CSA-Q224-b1": [0, 4],
    # Catalog one-to-many — Request→RITM, RITM→Approvals, RITM→Catalog Tasks
    "csa-snow-CSA-Q235-b1": [1, 2, 3],
    # Update multiple records — List Editor + Update Selected Action
    "csa-snow-CSA-Q237-b1": [0, 4],
    # Flow Designer advantages — Reduces technical debt, Less manual scripting, 3rd party integration
    "csa-snow-CSA-Q238-b1": [2, 3, 4],
    # Default tables — User, Incident, Task
    "csa-snow-CSA-Q240-b1": [0, 2, 4],
    # Platform interfaces — Now Mobile Apps, Service Portals, Now Platform UI
    "csa-snow-CSA-Q242-b1": [0, 3, 4],
    # Add fields to form — Configure > Form Layout + Configure > Form Design
    "csa-snow-CSA-Q249-b1": [1, 2],
    # Task children — Problem, Incident, Change Request
    "csa-snow-CSA-Q257-b1": [1, 4, 5],
    # Catalog order — sc_req_item + sc_task
    "csa-snow-CSA-Q260-b1": [0, 1],
    # Tag visibility — Groups and Users, Me, Everyone
    "csa-snow-CSA-Q266-b1": [0, 1, 3],
    # Notification fields — Conditions, Recipients, Content
    "csa-snow-CSA-Q270-b1": [2, 3, 4],
    # 3 key CMDB tables — cmdb, cmdb_rel_ci, cmdb_ci
    "csa-snow-CSA-Q274-b1": [0, 2, 5],
    # Catalog test best practices — Activate flows, Impersonate, Requester has manager
    "csa-snow-CSA-Q276-b1": [0, 2, 3],
    # Included workflows — Customer, Employee, IT
    "csa-snow-CSA-Q279-b1": [1, 4, 5],
    # Client script types — onSubmit, onCellEdit, onLoad, onChange
    "csa-snow-CSA-Q284-b1": [0, 2, 3, 5],
    # App Navigator search — Modules, Apps, Favorites, History
    "csa-snow-CSA-Q288-b1": [1, 2, 3, 4],
    # CMDB populate products — Discovery + IntegrationHub ETL
    "csa-snow-CSA-Q293-b1": [0, 1],
    # Filter condition components — Operator, Value, Field
    "csa-snow-CSA-Q299-b1": [0, 2, 4],
    # Group by category — list Context Menu Group By + Category column Context Menu
    "csa-snow-CSA-Q305-b1": [0, 4],
    # Add field to form — Form Layout + Form Designer
    "csa-snow-CSA-Q308-b1": [1, 2],
    # Target table for import — Global scope + write to other apps + Existing app scope
    "csa-snow-CSA-Q318-b1": [1, 3, 4],
    # Tablet + accessories — Variable set + Catalog Item with checkbox vars + Order Guide variant
    "csa-snow-CSA-Q325-b1": [0, 3, 4],
    # 3 security modules — System Properties > Security + Access Control (ACL) + High Security Settings
    "csa-snow-CSA-Q331-b1": [0, 4, 6],
    # BR timing options — Async, Display, After, Before
    "csa-snow-CSA-Q335-b1": [0, 3, 4, 5],
    # View fields on Incident — Tables & Columns + Dictionary
    "csa-snow-CSA-Q342-b1": [0, 1],
    # Assign task from list — checkbox + UI action OR double-click value
    "csa-snow-CSA-Q376":    [1, 2],
}

# Single-answer fixes where the marked-correct option was demonstrably wrong.
SINGLE_FIXES = {
    # Update payload stored in sys_update_xml (Customer Updates table) — doc-confirmed.
    "csa-snow-CSA-Q417": {
        "new_correct": [1],
        "explanation": "Update payloads are stored in the Customer Updates table (sys_update_xml). Each record holds the XML payload of one configuration change captured in an update set; the parent set lives in sys_update_set.",
    },
    # IntegrationHub spokes are distributed via the ServiceNow Store — doc-confirmed.
    "csa-snow-CSA-Q61": {
        "new_correct": [4],
        "explanation": "Prebuilt IntegrationHub spokes are distributed through the ServiceNow Store.",
    },
    # Default Update Set captures form/configuration changes, NOT homepages.
    "csa-snow-CSA-Q437": {
        "new_correct": [1],
        "explanation": "Update Sets capture configuration changes (e.g., form layout) by default. Homepages, data, scheduled jobs and database changes are NOT captured by default — they must be manually added.",
    },
    # Access Control Rules (ACLs) restrict access to files/data — Application Scope organizes apps.
    "csa-snow-CSA-Q161-b1": {
        "new_correct": [2],
        "explanation": "Access Control Rules (ACLs) protect applications by restricting access to specific tables, fields, records, and files based on roles, conditions, and scripts.",
    },
}

# Questions whose options list has a casing-only duplicate. The original
# dataset has both "Incident.Major_Incident" (option 0) and "incident.major_incident"
# (option 4) — equivalent answers. Replace the capitalized variant with a clearly
# different distractor so the question has a unique correct choice.
OPTION_REPLACEMENTS = {
    "csa-snow-CSA-Q255": {"replace_index": 0, "new_text": "Incident{Major_Incident}"},
    "csa-snow-CSA-Q72-b1": {"replace_index": 0, "new_text": "Incident{Major_Incident}"},
}


def remove_choose_n_stem(text: str) -> str:
    return re.sub(r"\s*\(\s*choose\s+\w+\s*\.?\s*\)\s*", " ", text, flags=re.I).strip()


def apply(csa):
    changed_ids = []
    notes = []

    for qid, new_correct in CHOOSE_N.items():
        q = next((x for x in csa if x["id"] == qid), None)
        if not q:
            notes.append({"id": qid, "kind": "missing_question"})
            continue
        old = list(q.get("correct") or [])
        n_opts = len(q.get("options") or [])
        nc = [i for i in new_correct if 0 <= i < n_opts]
        if nc != new_correct:
            notes.append({"id": qid, "kind": "out_of_range", "wanted": new_correct, "applied": nc})
        q["correct"] = nc
        changed_ids.append({"id": qid, "from": old, "to": nc, "kind": "choose_n"})

    for qid, spec in SINGLE_FIXES.items():
        q = next((x for x in csa if x["id"] == qid), None)
        if not q:
            notes.append({"id": qid, "kind": "missing_question"})
            continue
        old = list(q.get("correct") or [])
        q["correct"] = spec["new_correct"]
        if "explanation" in spec:
            q["explanation"] = spec["explanation"]
        changed_ids.append({"id": qid, "from": old, "to": spec["new_correct"], "kind": "single_fix"})

    for qid, spec in OPTION_REPLACEMENTS.items():
        q = next((x for x in csa if x["id"] == qid), None)
        if not q:
            notes.append({"id": qid, "kind": "missing_question"})
            continue
        idx = spec["replace_index"]
        opts = q.get("options") or []
        if 0 <= idx < len(opts):
            old_text = opts[idx]
            opts[idx] = spec["new_text"]
            changed_ids.append({"id": qid, "kind": "option_replaced", "index": idx,
                                "from": old_text, "to": spec["new_text"]})
        else:
            notes.append({"id": qid, "kind": "replace_out_of_range"})

    return changed_ids, notes


def main():
    paths = ["quiz-questions.json", "data/quiz/questions.json"]
    all_changes = None
    for p in paths:
        with open(p, encoding="utf-8") as f:
            data = json.load(f)
        csa = data["csa"]
        changes, notes = apply(csa)
        if all_changes is None:
            all_changes = (changes, notes)
        with open(p, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        print(f"Wrote {p}: {len(changes)} changes")

    return all_changes


if __name__ == "__main__":
    changes, notes = main()
    print(f"\nTotal changes: {len(changes)}")
    if notes:
        print("Notes:")
        for n in notes:
            print(" ", n)
