"""Produce csa-validation-report.json summarizing every fix in this validation pass.

It re-reads the live data and the original main-branch data to compute the diff,
then attaches a doc/source rationale per question.
"""
import json
import subprocess
from collections import defaultdict


SOURCES = {
    "csa-snow-CSA-Q5-b1": "ServiceNow Shared Responsibility Model white paper — customer responsibilities include identity/access management and data encryption configuration.",
    "csa-snow-CSA-Q8-b1": "ServiceNow UI Policy Actions reference — actions can set Visible, Mandatory, Read-only (Disabled).",
    "csa-snow-CSA-Q9-b1": "Table Builder requires admin or app_engine_admin per ServiceNow product docs.",
    "csa-snow-CSA-Q17-b1": "CMDB concepts per ServiceNow docs: configuration items live in tables/fields backed by a database, support service processes, and can be visualized via Dependency Views.",
    "csa-snow-CSA-Q19-b1": "Form Designer interface: Field Navigator (left), Field Picker, Form Layout canvas.",
    "csa-snow-CSA-Q20-b1": "ServiceNow notification methods: Email, SMS, Meeting Invitation (push to mobile is separate).",
    "csa-snow-CSA-Q24-b1": "Business Rule definition requires: Table, When (timing), Condition, Script — per System Definition > Business Rules docs.",
    "csa-snow-CSA-Q28-b1": "Context menus open via right-click on the header OR by clicking the context-menu icon.",
    "csa-snow-CSA-Q32-b1": "Table inheritance: Task is base; Incident extends Task (child of Task, parent of Super Incident); Super Incident extends Incident.",
    "csa-snow-CSA-Q37-b1": "Common related-list buttons: New, Edit, Add.",
    "csa-snow-CSA-Q41-b1": "Knowledge categories: by default managed by Knowledge Managers and Knowledge Owners.",
    "csa-snow-CSA-Q46-b1": "Basic Configuration UI16 settings include Banner Image, Browser Tab Title, and System Date Format.",
    "csa-snow-CSA-Q51-b1": "Knowledge search supports sort by Most recent update, Popularity, Relevancy.",
    "csa-snow-CSA-Q52-b1": "Reports can be created from the list column heading (right-click > Bar Chart…) and from Reports > Create New / Statistics.",
    "csa-snow-CSA-Q55-b1": "User menu offers Logout, Elevate Roles, Impersonate User (when permitted).",
    "csa-snow-CSA-Q57-b1": "Related list collector entries use the Table->Field syntax.",
    "csa-snow-CSA-Q81-b1": "System Properties > Basic Configuration UI16 manages Browser tab title, Module text color, Base theme, Header background color, and Banner Image.",
    "csa-snow-CSA-Q82-b1": "Flow Designer common core actions include Create Record, Ask for Approval, Look Up Record, Wait for Condition.",
    "csa-snow-CSA-Q86-b1": "Provisioning a new IT user means: create the account, add to the relevant groups (Hardware, Network).",
    "csa-snow-CSA-Q89-b1": "List UI Action types: List Banner Button, List Bottom Button, List Choice, List Context Menu, List Link — picked here as Buttons/Choices/Context Menu/Links.",
    "csa-snow-CSA-Q93-b1": "Per docs.servicenow.com and ServiceNow community, default Update Sets do NOT capture: Homepages, Data, Published Workflows, Report Definitions.",
    "csa-snow-CSA-Q98-b1": "Creating a custom table auto-generates ACLs for create, read, write, delete.",
    "csa-snow-CSA-Q114-b1": "Impersonation requires admin or impersonator role (docs.servicenow.com platform administration).",
    "csa-snow-CSA-Q116-b1": "Flow Designer benefits: natural-language flow descriptions, no-code/low-code, easy 3rd party integration via spokes.",
    "csa-snow-CSA-Q130-b1": "UI Policy can set fields hidden, read-only, or mandatory.",
    "csa-snow-CSA-Q132-b1": "Service Mapping + Discovery populate CMDB; CMDB stores the model — these three products together support tracking infrastructure for a service.",
    "csa-snow-CSA-Q142-b1": "Group-based assignment supports skill-based routing, on-call schedules, availability, and self-pickup via 'My Groups Work'.",
    "csa-snow-CSA-Q156-b1": "Create a new table via System Definition > Tables OR System Definition > Tables & Columns.",
    "csa-snow-CSA-Q168-b1": "Events are generated by Business Rules (gs.eventQueue) and Workflow activities (Run Script / Event activity).",
    "csa-snow-CSA-Q169-b1": "Best practice: assign roles to groups, add users to groups.",
    "csa-snow-CSA-Q176-b1": "ACL permission requirements: Roles, Conditional Expressions, Scripts.",
    "csa-snow-CSA-Q177-b1": "Supported user authentication methods: Local database, LDAP, SSO/SAML.",
    "csa-snow-CSA-Q196-b1": "Reports page audience sections: Group, My reports, Global, All.",
    "csa-snow-CSA-Q201-b1": "Data Source types: Local file (XML/CSV/Excel), JDBC, LDAP, Network/FTP server.",
    "csa-snow-CSA-Q204-b1": "Form UI Action types: Form Button, Form Context Menu, Form Link.",
    "csa-snow-CSA-Q208-b1": "Field label can be changed via right-click > Configure Label OR by editing the dictionary (Configure Dictionary).",
    "csa-snow-CSA-Q209-b1": "When extending a table, only fields not in the base table (i.e., fields specific to the extended table) need to be created.",
    "csa-snow-CSA-Q214-b1": "Tasks can be assigned to Users or Groups.",
    "csa-snow-CSA-Q224-b1": "A user who sees only Self Service is missing the itil role — either direct or via group membership.",
    "csa-snow-CSA-Q235-b1": "Service Catalog one-to-many: Request → Requested Items, Requested Item → Approvals, Requested Item → Catalog Tasks.",
    "csa-snow-CSA-Q237-b1": "Bulk update via List Editor (in-line list edit) and the Update Selected UI action.",
    "csa-snow-CSA-Q238-b1": "Flow Designer reduces technical debt, requires less manual scripting, and smoothly integrates with 3rd-party systems via spokes.",
    "csa-snow-CSA-Q240-b1": "Default base tables include User (sys_user), Task, Incident (extends Task).",
    "csa-snow-CSA-Q242-b1": "Platform interfaces: Now Mobile Apps, Service Portals, Now Platform UI (UI16/Next Experience).",
    "csa-snow-CSA-Q249-b1": "Add fields via Configure > Form Layout (slushbucket) or Configure > Form Designer.",
    "csa-snow-CSA-Q257-b1": "Out-of-box Task children include Problem, Incident, Change Request (and others).",
    "csa-snow-CSA-Q260-b1": "Catalog order creates a sc_req_item (RITM) record plus a sc_task (Catalog Task) when the workflow defines one.",
    "csa-snow-CSA-Q266-b1": "Tag visibility options: Me, Groups and Users, Everyone.",
    "csa-snow-CSA-Q270-b1": "Notification requires: When/Condition (when sent), Who (recipients), What (content).",
    "csa-snow-CSA-Q274-b1": "Three CMDB key tables: cmdb (base CI), cmdb_ci (core CI), cmdb_rel_ci (relationships) — confirmed by docs.servicenow.com and the CSA exam blueprint.",
    "csa-snow-CSA-Q276-b1": "Catalog test best practices: activate latest flow, impersonate the requester, ensure requester has a manager set so approval routing works.",
    "csa-snow-CSA-Q279-b1": "ServiceNow workflow families: Customer Workflows, Employee Workflows, IT Workflows.",
    "csa-snow-CSA-Q284-b1": "Client Script types: onLoad, onChange, onSubmit, onCellEdit.",
    "csa-snow-CSA-Q288-b1": "App Navigator search surfaces Applications, Modules, Favorites, and History.",
    "csa-snow-CSA-Q293-b1": "Discovery and IntegrationHub ETL are the two ServiceNow products used to discover/populate the CMDB.",
    "csa-snow-CSA-Q299-b1": "Filter condition components: Field, Operator, Value.",
    "csa-snow-CSA-Q305-b1": "Group By Category: list Context Menu > Group By > Category, or right-click the Category column > Group By Category.",
    "csa-snow-CSA-Q308-b1": "Add a field via Configure > Form Layout OR Configure > Form Designer.",
    "csa-snow-CSA-Q318-b1": "Target tables for import: global scope, tables that allow writes across scopes, and tables in the existing application scope.",
    "csa-snow-CSA-Q325-b1": "Tablet+accessories: build a Catalog Item with a variable set, separate items + Order Guide, or checkbox variables per accessory.",
    "csa-snow-CSA-Q331-b1": "Common admin security modules: System Properties > Security, System Security > Access Control (ACL), System Security > High Security Settings.",
    "csa-snow-CSA-Q335-b1": "Business Rule timing options (When): Before, After, Async, Display.",
    "csa-snow-CSA-Q342-b1": "View Incident fields via Tables & Columns module or System Dictionary.",
    "csa-snow-CSA-Q376": "From a list: tick the row and use the 'Assign To Me' UI action header button, or double-click the Assigned to field, enter your name, and click the green check.",
    "csa-snow-CSA-Q417": "sys_update_xml (Customer Updates) stores each captured XML payload; sys_update_set holds the parent set record — per ServiceNow docs and the community 'sys_update_xml' table reference.",
    "csa-snow-CSA-Q61": "IntegrationHub spokes are distributed via the ServiceNow Store (store.servicenow.com).",
    "csa-snow-CSA-Q437": "Default Update Sets capture configuration changes (forms, business rules, scripts, UI policies) but not data, scheduled jobs, schedule records, homepages, or dashboards.",
    "csa-snow-CSA-Q161-b1": "Access Control Rules (ACLs) — not Application Scope — restrict access to tables, fields, records, and files.",
    "csa-snow-CSA-Q255": "Removed casing-only duplicate option ('Incident.Major_Incident') so the question has a single unambiguous correct answer (incident.major_incident).",
    "csa-snow-CSA-Q72-b1": "Same casing-only deduplication as csa-snow-CSA-Q255.",
}


def run(cmd):
    return subprocess.check_output(cmd, shell=True, text=True)


def load_main_csa():
    j = run("git show origin/main:quiz-questions.json")
    return {q["id"]: q for q in json.loads(j)["csa"]}


def main():
    with open("quiz-questions.json", encoding="utf-8") as f:
        new_csa = {q["id"]: q for q in json.load(f)["csa"]}
    old_csa = load_main_csa()

    diffs = []
    for qid, nq in new_csa.items():
        oq = old_csa.get(qid)
        if not oq:
            continue
        change = {}
        if list(oq.get("correct") or []) != list(nq.get("correct") or []):
            change["correct"] = {"from": oq.get("correct"), "to": nq.get("correct")}
        if (oq.get("options") or []) != (nq.get("options") or []):
            change["options"] = {"from": oq.get("options"), "to": nq.get("options")}
        if (oq.get("explanation") or "") != (nq.get("explanation") or "") and nq.get("explanation"):
            change["explanation_updated"] = True
        if change:
            diffs.append({
                "id": qid,
                "topic": nq.get("topic"),
                "question": nq.get("q", "")[:240],
                "source": SOURCES.get(qid, ""),
                **change,
            })

    by_topic = defaultdict(int)
    for d in diffs:
        by_topic[d["topic"]] += 1

    report = {
        "generated_by": "scripts/csa_apply_fixes.py + scripts/csa_build_report.py",
        "validation_scope": "Internal consistency checks + sampled cross-validation against docs.servicenow.com and ServiceNow community references",
        "csa_question_count": len(new_csa),
        "questions_changed": len(diffs),
        "changes_by_topic": dict(sorted(by_topic.items())),
        "categories_of_fix": {
            "choose_n_under_marked": "Questions whose stem said 'Choose N' but only 1 option was marked correct; correct[] re-populated with full set per CSA canonical answers.",
            "single_answer_wrong": "Questions whose marked-correct option was demonstrably wrong vs. official docs (sys_update_xml, ServiceNow Store, Access Control Rules, default Update Set capture).",
            "duplicate_option_dedup": "Casing-only duplicate options replaced with a distinct distractor so each question has a single unambiguous correct answer.",
        },
        "fixes": diffs,
    }
    with open("csa-validation-report.json", "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
    print(f"Wrote csa-validation-report.json with {len(diffs)} fixes across {len(by_topic)} topics")


if __name__ == "__main__":
    main()
